version: "3.8"

services:
    nginx:
        container_name: ${DOCKER_APP_NAME}_nginx
        image: nginx
        ports:
            - ${DOCKER_APP_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        depends_on:
            - php
        networks:
            - innerappfootballnet

    php:
        container_name: ${DOCKER_APP_NAME}_php
        build:
            context: docker/php-fpm
        volumes:
            - ./:/var/www
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
        environment:
            PHP_IDE_CONFIG: "serverName=PhpServerDocker"
        networks:
            - innerappfootballnet

    db:
        container_name: ${DOCKER_APP_NAME}_db
        image: mysql:8.0.27
        command: [ --default-authentication-plugin=mysql_native_password ]
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/logs/mysql:/var/log/mysql
        ports:
            - ${DOCKER_MYSQL_PORT}:3306
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - innerappfootballnet

    adminer:
        image: adminer
        container_name: ${DOCKER_APP_NAME}_adminer
        restart: unless-stopped
        ports:
            - ${DOCKER_ADMINER_PORT}:8080
        depends_on:
            - db
        environment:
            ADMINER_DEFAULT_DB_DRIVER: db
            ADMINER_DEFAULT_SERVER: db
            ADMINER_DESIGN: hever
            ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
        networks:
            - innerappfootballnet

networks:
    innerappfootballnet:
        driver: bridge
